#ifndef _ARCHCONS_H_
#define _ARCHCONS_H_

typedef const unsigned int APP_UINT;

//APP_UINT MODE_SELECT       = 1000;
APP_UINT MODE_CONSTRUCTION = 1000u;
APP_UINT MODE_ADJUSTMENT   = 2000u;
APP_UINT MODE_ZOOM         = 3000u;



// Construction mode premitive's constants

APP_UINT CONSTRUCT_WALL      = 1100u;
APP_UINT CONSTRUCT_CWALL     = 1200u;
APP_UINT CONSTRUCT_PILLAR    = 1300u;
APP_UINT CONSTRUCT_STAIRS    = 1400u;
APP_UINT CONSTRUCT_BASEPLANE = 1500u;
APP_UINT CONSTRUCT_CEILPLANE = 1600u;
APP_UINT CONSTRUCT_CHAIROBJ  = 1700u;
APP_UINT CONSTRUCT_SPIRALSTAIR=1800u;
APP_UINT CONSTRUCT_FIXTUREWALL=1900u;
APP_UINT CONSTRUCT_TABLEOBJ	=2000u;
APP_UINT CONSTRUCT_SOFAOBJ	=3000u;
// endof consturction objects

// Adjustment mode constants

APP_UINT ADJUSTMENT_SELECT  = 2100u;
APP_UINT ADJUSTMENT_DELETE  = 2200u;
APP_UINT ADJUSTMENT_ROTATE  = 2300u;
APP_UINT ADJUSTMENT_MOVE    = 2400u;
APP_UINT ADJUSTMENT_RESIZE  = 2500u;

//end of adjustment mode

// define fixture type constants

APP_UINT FIXTURE_DOOR         = 100u;
APP_UINT FIXTURE_DOOR_SINGLE  = 101u;
APP_UINT FIXTURE_DOOR_DOUBLE  = 110u;

APP_UINT FIXTURE_WINDOW       = 200u;

APP_UINT BUILDING_ELEMENT_WALL         = 5100u;
APP_UINT BUILDING_ELEMENT_CURVEDWALL   = 5200u;	
APP_UINT BUILDING_ELEMENT_ROUNDPILLAR  = 5300u;
APP_UINT BUILDING_ELEMENT_SQUAREPILLAR = 5400u;
APP_UINT BUILDING_ELEMENT_STAIRS       = 5500u;
APP_UINT BUILDING_ELEMENT_CEILING      = 5600u; 
APP_UINT BUILDING_ELEMENT_CHAIR1     = 5700u;
APP_UINT BUILDING_ELEMENT_CHAIR2     = 5800u;
APP_UINT BUILDING_ELEMENT_CHAIR3     = 5900u;
APP_UINT BUILDING_ELEMENT_CHAIR4     = 6000u;
APP_UINT BUILDING_ELEMENT_CHAIR5     = 6100u;
APP_UINT BUILDING_ELEMENT_CHAIRTYPE  =6200u;
APP_UINT BUILDING_ELEMENT_SPIRALSTAIR= 6300u;
APP_UINT BUILDING_ELEMENT_FIXTUREWALL= 6400u;
APP_UINT BUILDING_ELEMENT_TABLE1     = 6500u;
APP_UINT BUILDING_ELEMENT_TABLE2     = 6600u;
APP_UINT BUILDING_ELEMENT_TABLE3     = 6700u;
APP_UINT BUILDING_ELEMENT_TABLE4     = 6800u;
APP_UINT BUILDING_ELEMENT_TABLE5     = 6900u;

APP_UINT BUILDING_ELEMENT_SOFA1     = 7000u;
APP_UINT BUILDING_ELEMENT_SOFA2     = 7100u;
APP_UINT BUILDING_ELEMENT_SOFA3     = 7200u;
APP_UINT BUILDING_ELEMENT_SOFA4     = 7300u;
APP_UINT BUILDING_ELEMENT_SOFA5     = 7400u;
#endif
