//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Arch.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ARCHGL_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDR_ARCHTYPE                    129
#define IDR_TBRAPPMODE                  132
#define IDR_TBRELEMENT                  134
#define IDD_FIXTURE                     138
#define IDD_PILLAR_PROPERTIES           139
#define IDD_FLOOR_VIEW                  140
#define IDD_DIALOG_PILLAR               142
#define IDD_DIALOG_STAIR                144
#define IDD_DIALOG_STRAIGHT_WALL        145
#define IDD_DIALOG_CURVED_WALL          148
#define IDB_BITMAP1                     149
#define IDR_TBOBJECT                    152
#define IDD_DIALOG1                     154
#define IDD_DIALOG2                     155
#define IDD_DIALOG3                     156
#define IDD_DIALOG4                     157
#define IDD_DIALOG_CEILING              159
#define IDD_WALL                        160
#define IDD_DIALOG_TABLE                161
#define IDD_DIALOG5                     162
#define IDD_DIALOG_SOFA                 163
#define IDC_PREVIEW                     1000
#define IDC_STATIC_PILLAR_PREVIEW       1000
#define IDC_BtnCHK                      1001
#define IDC_BUTTON_COLOR                1001
#define IDC_LISTFIXTURE                 1002
#define IDC_RADIO_TYPE_CYLINDER         1002
#define IDC_RADIO_TYPE_CUBIC            1003
#define IDC_EDIT_WIDTH                  1004
#define IDC_PTYPE                       1005
#define IDC_RADIO_WIDTH_1               1005
#define IDC_PTYPE2                      1006
#define IDC_RADIO_WIDTH_1andHalf        1006
#define IDC_BTN_COLOR                   1007
#define IDC_RADIO_WIDTH_2               1007
#define IDC_EDIT_FLOORNUM               1009
#define IDC_RADIO_WIDTH_3               1011
#define IDC_RADIO_WIDTH_4               1012
#define IDC_ttypeSTATIC                 1014
#define IDC_ttypeCOMBO1                 1015
#define IDC_stypeSTATIC                 1016
#define IDC_stypeCOMBO1                 1017
#define IDC_ctypeSTATIC                 1018
#define IDC_ctypeCOMBO1                 1019
#define IDC_RADIO_WALL_4                1020
#define IDC_RADIO_WALL_9                1021
#define IDC_RADIO_WALL_13               1022
#define IDC_RADIO_DOOR_2x7              1023
#define IDC_RADIO_DOOR_3x7              1024
#define IDC_RADIO_DOOR_4x7              1025
#define IDC_RADIO_WINDOW_2x3            1026
#define IDC_RADIO_WINDOW_3x3            1027
#define IDC_RADIO_WINDOW_3x4            1028
#define IDC_RADIO_WINDOW_4x4            1029
#define IDC_BASE_POINT                  1030
#define IDC_CHAIR1                      1032
#define IDC_CHAIR2                      1033
#define IDC_CHAIR3                      1034
#define IDC_CHAIR4                      1035
#define IDC_RADIO_COL1                  1036
#define IDC_CHAIR5                      1036
#define IDC_RADIO_TEXTURE1              1037
#define IDC_CEILING_POINT               1037
#define IDC_RADIO_COL2                  1038
#define IDC_RADIO_TEXTURE2              1039
#define IDC_TOP_POINT                   1040
#define IDC_Base                        1042
#define IDC_STATIC_S1                   1044
#define IDC_Top                         1044
#define IDC_STATIC_S2                   1045
#define IDC_STATIC_Preview              1048
#define IDC_BTN_WINDOW_CLR              1049
#define IDC_RADIO_Width                 1049
#define IDC_CHECK_DOOR                  1050
#define IDC_RADIO6                      1050
#define IDC_CHECK_WINDOW                1051
#define IDC_RADIO7                      1051
#define IDC_BTN_DOOR_CLR                1052
#define IDC_BTN_MOVE_LEFT               1053
#define IDC_STATIC_Preview1             1053
#define IDC_BTN_MOVE_RIGHT              1054
#define IDC_SELECT_DOOR                 1055
#define IDC_SELECT_WINDOW               1056
#define IDC_SideA                       1056
#define IDC_STATIC_DOOR                 1057
#define IDC_T1                          1057
#define IDC_STATIC_WINDOW               1058
#define IDC_SideB                       1058
#define IDC_T2                          1059
#define IDC_WallPreB                    1060
#define IDC_RADIO_table                 1061
#define IDC_RADIO2                      1062
#define IDC_RADIO3                      1063
#define IDC_CEIL_COLOR                  1063
#define IDC_RADIO4                      1064
#define IDC_SPIRAL_COLOR                1064
#define IDC_RADIO5                      1065
#define IDC_RADIO_sofa                  1065
#define IDC_RADIO8                      1066
#define IDC_RADIO9                      1067
#define IDC_RADIO10                     1068
#define IDC_RADIO11                     1069
#define ID_BUILD_WALL                   32771
#define ID_BUILD_CURVEDWALL             32772
#define ID_BUILD_PILLAR                 32773
#define ID_BUILD_STAIRS                 32774
#define ID_BUILD_BASEPLANE              32775
#define ID_BUILD_CEILLING               32776
#define ID_VIEW_FLOOR                   32777
#define ID_VIEW_3DVIEW                  32779
#define ID_EDIT_SELECTELEMENT           32780
#define ID_EDIT_MOVEELEMENT             32781
#define ID_EDIT_ROTATEELEMENT           32782
#define ID_EDIT_RESIZEELEMENT           32783
#define ID_EDIT_DELETEELEMENT           32784
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUILD_FLOOR                  32798
#define ID_VIEW_2DVIEW                  32799
#define ID_OBJECT_TABLE                 32802
#define ID_OBJECT_CHAIR                 32803
#define ID_OBJECT_SOFA                  32804
#define ID_BUILD_CELLING                32805
#define ID_BUILD_CEIL                   32806
#define ID_BBUILD_SPIRALSTAIR           32807
#define ID_BUILD_FIXTURE                32808
#define ID_VIEW_VIEWFLOOR               32812
#define ID_VIEW_NEWFLOOR                32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
